version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor: win/default
    environment:
      version: '5.4.0'
      binaryversion: '11'
      build: '8'
    steps:
      - checkout
      - run: iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - run: Install-Module -Name 7Zip4Powershell -Force -Scope CurrentUser
      - run: choco install -y msys2
      - run: |
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest -UseBasicParsing -Uri "https://code.call-cc.org/releases/$Env:version/chicken-$Env:version.tar.gz" -OutFile '.\chicken.tar.gz'
          7z x chicken.tar.gz
          7z x chicken.tar
          Remove-Item -Force chicken.tar.gz
          Remove-Item -Force chicken.tar
          mv chicken-* chickenbuild
      - run: C:\tools\msys64\usr\bin\env MSYSTEM=MINGW64 /bin/bash -l -c 'pacman -S --needed --noconfirm pactoys patch'
      - run: C:\tools\msys64\usr\bin\env MSYSTEM=MINGW64 /bin/bash -l -c 'pacboy -Sy --needed --noconfirm binutils:x make:x gcc:x gettext:x readline:x'
      - run: C:\tools\msys64\usr\bin\env MSYSTEM=MINGW64 /bin/bash -l -c 'cd /c/Users/circleci/project/; patch -p0 < chickenbuild.patch'
      - run: C:\tools\msys64\usr\bin\env MSYSTEM=MINGW64 /bin/bash -l -c "export CFLAGS='-O2 -Wno-unused-variable -Wno-unused-but-set-variable -Wno-error=incompatible-pointer-types'; export C_TARGET_INSTALL_PROGRAM='copy /Y'; mingw32-make PLATFORM=mingw-msys ARCH=x86-64 PREFIX=C:/tools/chicken -C /c/Users/circleci/project/chickenbuild"
      - run: .\build.ps1
      - run: choco apikey --key $Env:CHOCO_API_KEY --source https://push.chocolatey.org
      - run: choco push chicken.$Env:version.$Env:build.nupkg --source https://push.chocolatey.org
