version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    environment:
      version: '5.2.0'
      binaryversion: '11'
    steps:
      - checkout
      - run: iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - run: Install-Module -Name 7Zip4Powershell -Force -Scope CurrentUser
      - run: choco install -y msys2
      - run: |
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest -UseBasicParsing -Uri "https://code.call-cc.org/releases/$Env:version/chicken-$Env:version.tar.gz" -OutFile '.\chicken.tar.gz'
          7z x chicken.tar.gz
          7z x chicken.tar
          Remove-Item -Force chicken.tar.gz
          Remove-Item -Force chicken.tar
          mv chicken-* chickenbuild
      - run: C:\tools\msys64\usr\bin\bash.exe --login -c 'pacboy -Sy --needed --noconfirm binutils:x make:x gcc:x gettext:x readline:x'
      - run: $env:Path+=";C:\tools\msys64\mingw64\bin"; mingw32-make.exe -C chickenbuild PLATFORM=mingw ARCH=x86-64 PREFIX=C:/tools/chicken
      - run: .\build.ps1
      - run: choco apikey --key $Env:CHOCO_API_KEY --source https://push.chocolatey.org
      - run: choco push chicken.$Env:version.nupkg --source https://push.chocolatey.org
